import numpy as np
print(np.random.rand(2,9))
a1 = np.random.uniform(-10,10,(4,3))
b2 = np.random.normal(0,10,(4,3))
c3 = np.random.standard_normal((4,3))
d4 = np.random.zipf(2,(4,3))
print()
print("Normal distribution")
print (a1)
print()
print("Standart normal distribution")
print (b2)
print()
print("Uniform distribution")
print (c3)
print()
print("Zip distribution")
print (d4)
print("Rounded b2")
print(np.around(b2,2))
print("Min: ", np.min(b2))
print("Max: ", np.max(b2))
print("2nd row avg: ", b2[1,:].mean(), ", last column avg: ", b2[:,-1:].mean())
print("fix() rounding: ")
print(np.fix(a1))
print("rint() rounding: ")
print(np.rint(a1))
arr = np.random.randint(100000,10000000,(5,5))
print(arr)
print(np.round(arr, -3))